services:
  ecommerce-mongo:
    image: mongo:latest
    container_name: ecommerce_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: 1234
    volumes:
      - mongo_data:/data/db   # named volume for persistence
    ports:
      - "${MONGO_PORT:-27017}:27017"
    networks:
      - ecommerce

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    command: 'http --domain=monkfish-organic-viper.ngrok-free.app --host-header=rewrite host.docker.internal:5000'
    ports:
      - '4041:4040'
    expose:
      - '4040'
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  ecommerce:
    driver: bridge


