services:
  ecommerce-mongo:
    image: mongo:latest
    container_name: ecommerce_mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD:-password123}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE:-mydatabase}
    volumes:
      - mongo_data:/data/db
    ports:
      - "${MONGO_PORT:-27018}:27017"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - ecommerce

  ngrok:
    image: ngrok/ngrok:latest
    environment:
      NGROK_AUTHTOKEN: ${NGROK_AUTH_TOKEN}
    command: 'http --domain=monkfish-organic-viper.ngrok-free.app --host-header=rewrite host.docker.internal:5000'
    ports:
      - '4041:4040'
    expose:
      - '4040'
    restart: unless-stopped

volumes:
  mongo_data:
    driver: local

networks:
  ecommerce:
    driver: bridge


